name: ci

on:
    push:
        branches:
            - main

jobs:
    build-amd64:
        runs-on: ubuntu-latest
        permissions:
            packages: write
        steps:
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: docker/setup-buildx-action@v3

            - uses: actions/checkout@v6

            - name: Set short rev
              id: rev_parse
              run: echo "git_rev=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: ghcr.io/futurgh/pegasus:${{ github.sha }}-amd64
                  build-args: GIT_REV=${{ steps.rev_parse.outputs.git_rev }}
                  cache-from: type=gha,scope=amd64
                  cache-to: type=gha,scope=amd64,mode=max

    build-arm64:
        runs-on: ubuntu-24.04-arm
        permissions:
            packages: write
        steps:
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: docker/setup-buildx-action@v3

            - uses: actions/checkout@v6

            - name: Set short rev
              id: rev_parse
              run: echo "git_rev=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: ghcr.io/futurgh/pegasus:${{ github.sha }}-arm64
                  build-args: GIT_REV=${{ steps.rev_parse.outputs.git_rev }}
                  cache-from: type=gha,scope=arm64
                  cache-to: type=gha,scope=arm64,mode=max

    merge:
        runs-on: ubuntu-latest
        needs: [build-amd64, build-arm64]
        permissions:
            packages: write
        steps:
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Create multi-arch manifest
              run: |
                  docker buildx imagetools create -t ghcr.io/futurgh/pegasus:latest \
                      ghcr.io/futurgh/pegasus:${{ github.sha }}-amd64 \
                      ghcr.io/futurgh/pegasus:${{ github.sha }}-arm64
